import Head from 'next/head'
import Image from 'next/image'
import formImage from '../public/form.png'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import { motion as m } from 'framer-motion'

export default function Home() {
  const router = useRouter()

  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'Indonesia',
      terms: ''
    },
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, 'Name must be 20 charracters or less.')
        .required('Name is required.'),
      email: Yup.string()
        .email('Invalid email address.')
        .required('Email is required.'),
      terms: Yup.array()
        .required('Terms of service must be checked.')
    }),
    onSubmit: (values) => {
      console.log(values)
      router.push({ pathname: '/success', query: values })
    }
  })

  return (
    <m.div 
      initial={{ opacity: 0 }} 
      animate={{ opacity: 1 }} 
      exit={{ opacity: 0 }}
      className='absolute w-full'
    >
      <Head>
        <title>Formik React Form | NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center items-center">
        <form className="bg-white flex rounded-lg w-fit font-latoRegular" onSubmit={formik.handleSubmit}>
          <div className="flex-1 text-gray-700 p-10">
            <h1 className="text-3xl font-latoBold pb-2">Let's get started👋</h1>
            <p className="text-lg text-gray-500">
              Join our e-Learning platform today and unlock over 500+ curses and
              digital assets ready to download
            </p>

            <div className="mt-6">
              {/* Name input field */}
              <div className="pb-4">
                <label
                  htmlFor="name"
                  className={`block font-latoBold text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`}
                >
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:outline-teal-500"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Email input field */}
              <div className="pb-4">
                <label
                  htmlFor="email"
                  className={`block font-latoBold text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`}
                >
                  {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
                </label>
                <input
                  type="email"
                  name="email"
                  placeholder="Enter your email"
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:outline-teal-500"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              {/* Country input field */}
              <div className="pb-4">
                <label
                  htmlFor="country"
                  className="block font-latoBold text-sm pb-2"
                >
                  Country
                </label>
                <select name='country' className='border-2 border-gray-500 p-2 rounded-md w-full focus:outline-teal-500' value={formik.values.country} onChange={formik.handleChange}>
                  <option>Indonesia</option>
                  <option>Malaysia</option>
                  <option>Singapore</option>
                  <option>Thailand</option>
                </select>
              </div>
              {/* Terms of service */}
              <div className="pb-4">
                <label
                  htmlFor="terms"
                  className={`block font-latoBold text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`}
                >
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of service'}
                </label>
                <div className='flex items-center gap-2'>
                  <input
                    type="checkbox"
                    name="terms"
                    value='checked'
                    onChange={formik.handleChange}
                    className="w-4 h-4 border-2 appearance-none checked:bg-teal-500"
                  />
                  <p className='text-sm font-latoBold text-gray-500'>
                    I agree to the Terms and Service that my data will be taken and sold.
                  </p>
                </div>
              </div>
              <button type='submit' className='bg-teal-500 text-white text-md font-latoBold mt-6 py-3 rounded-lg w-full hover:bg-teal-400'>Start learning today!</button>
            </div>
          </div>
          <div className='flex-1 relative'>
            <Image src={formImage} fill priority className='object-cover rounded-lg' alt='form-learn' />
          </div>
        </form>
      </main>
    </m.div>
  );
}
